#!/usr/bin/env sh

BATTERY_THRESHOLD=10
NOTIFICATION_FLAG="/run/user/$UID/de/notification_flag"

BATTERY_LEVEL=$(upower -i $(upower -e | grep 'BAT') | grep -E "percentage" | grep -o '[0-9]\+%' | sed 's/%//')
BATTERY_STATE=$(upower -i $(upower -e | grep 'BAT') | grep -E "state" | awk '{print $2}')

if [[ "$BATTERY_STATE" == "discharging" && "$BATTERY_LEVEL" -le "$BATTERY_THRESHOLD" ]]; then
  if [[ ! -f "$NOTIFICATION_FLAG" ]]; then
    notify-send -u critical "󱐋 Time to recharge!" "Battery is down to $BATTERY_LEVEL%" -i battery-caution -t 30000
    touch "$NOTIFICATION_FLAG"
  fi
else
  rm -f "$NOTIFICATION_FLAG"
fi
