vim.cmd [[packadd packer.nvim]]

return require('packer').startup(function(use)
    use('wbthomason/packer.nvim')
    use('nvim-treesitter/nvim-treesitter')
    use('nvim-treesitter/nvim-treesitter-context')
    use('norcalli/nvim-colorizer.lua')
    use('folke/todo-comments.nvim')
    use('windwp/nvim-autopairs')
    use('nvim-lualine/lualine.nvim')
    use('nvim-lua/plenary.nvim')
    use('nvim-telescope/telescope.nvim')
    use('lewis6991/gitsigns.nvim')
    use('lukas-reineke/indent-blankline.nvim')
    use('VonHeikemen/lsp-zero.nvim')
    use('neovim/nvim-lspconfig')
    use('hrsh7th/cmp-nvim-lsp')
    use('hrsh7th/nvim-cmp')
    use('mhartington/formatter.nvim')
    use('williamboman/mason.nvim')
    use('williamboman/mason-lspconfig.nvim')
    use('j-hui/fidget.nvim')
    use('RRethy/vim-illuminate')
    use('HiPhish/rainbow-delimiters.nvim')
    use('smoka7/hop.nvim')
    use('otavioschwanck/arrow.nvim')
    use('nvim-tree/nvim-web-devicons')
    use('tpope/vim-surround')
    use('stevearc/conform.nvim')
    use('nvchad/volt')
    use('NvChad/menu')

    use('folke/tokyonight.nvim')
    use('dgox16/oldworld.nvim')
end)
