#!/usr/bin/env python

import argparse
import os
import shutil
import subprocess
from typing import List, Optional

PKG_MANAGER = "pacman"
AUR_MANAGER = "yay"

ABS_PATH = os.path.dirname(os.path.abspath(__file__))
HOME = os.path.expanduser("~")
ARGS = None

def check(path: str) -> bool:
    """
    Verifies whether a path exists or not.
    """
    return os.path.exists(path)


def ask(question: str) -> bool:
    """
    Prompt a yes/no question and return True if the user answers yes, otherwise False.
    """
    return input(f"{question} [Y/n]: ").lower() in ["y", "yes"]


def ask_remove(path: str, sudo: bool = False, skip: bool = False) -> bool:
    if not skip and not ask(f"Destination '{path}' already exists. Do you want to remove it?"):
        return False

    return os.system(f"{'sudo' if sudo else ''} rm -rf {path}") == 0


def link(src: str, dst: str) -> None:
    """
    Creates a symbolic link from source to destination. If `dst` exists,
    it asks for replacement, which is skipped if `ARGS.replace_all` is True.
    """
    src = f"{ABS_PATH}/{src}"

    if not check(src):
        print(f"Source '{src}' does not exists.")
        return

    if check(dst) and not ask_remove(dst, skip=ARGS.replace_all):
        print(f"Link creation canceled. '{dst}' was not removed.")
        return
    
    try:
        os.symlink(src, dst)
        print(f"Symbolic link created from '{src}' to '{dst}'.")
    except OSError as e:
        print(f"Error creating symbolic link: {e}.")

# TODO: make it a namespace instead of a class
class install:
    @staticmethod
    def with_mng(pkgs: List[str]) -> int:
        """
        Installs packages using the system package manager.

        Parameters:
            pkgs (List[str]): List of package names to install.

        Returns:
            int: Exit code of the installation process.
        """
        if not ARGS.install_pkg:
            print(f"Aborting installation of {', '.join(pkgs)} with {PKG_MANAGER} because '--install-pkg' is False.")
            return 256

        if not ask(f"Installing {', '.join(pkgs)} with {PKG_MANAGER}. Do you want to proceed?"):
            print(f"Aborting installation of {', '.join(pkgs)}.")
            return 256

        return os.system(f"sudo pacman -S --noconfirm {' '.join(pkgs)}")


    @staticmethod
    def with_yay(pkgs: List[str]) -> int:
        """
        Installs packages using the yay package manager.

        Parameters:
            pkgs (List[str]): List of package names to install.

        Returns:
            int: Exit code of the installation process.
        """
        if not ARGS.install_pkg:
            print(f"Aborting installation of {', '.join(pkgs)} with {AUR_MANAGER} because '--install-pkg' is False.")
            return 256

        return 0


    @staticmethod
    def with_git(repos: List[str], dest: str = "/tmp", flags: List[str] = []) -> List[int]:
        """
        Clones a Git repository to the specified destination.

        Parameters:
            repos (List[str]): The URL of the Git repository.
            dest (str): The destination directory for the clone. Defaults to "/tmp".

        Returns:
            int: A list of exit codes for each clone process.
        """
        if not ARGS.install_pkg:
            print(f"Skipping clone {', '.join(repos)} because '--install-pkg' is False.")
            return [256]

        codes = []
        for repo in repos:
            repo_dest = f"{dest}/{os.path.basename(repo).replace('.git', '')}"
            print(f"\nCloning {repo} into {repo_dest}:")

            if check(repo_dest) and not ask_remove(repo_dest, sudo=True):
                print(f"Repository clonning canceled. '{repo_dest}' was not removed.")
                continue

            code = subprocess.call(f"git clone {' '.join(flags)} {repo} {repo_dest}", shell=True)
            if code == 0:
                print(f"Cloned Git repository '{repo}' to '{repo_dest}'.")
            else:
                print(f"Error cloning Git repository {repo}: code {code}")
            codes.append(code)

        return codes


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="")

    parser.add_argument("-r", "--replace-all", action="store_true", help="Replace existing destinations without prompting.")
    parser.add_argument("-i", "--install-pkg", action="store_true", help="Install required packages. Running without it may lead to errors as the symbolic links will be maded anyway.")
    parser.add_argument("--sddm", action="store_true", help="Install and enable the SDDM.")

    ARGS = parser.parse_args()

    # $HOME/projects is the directory used for armazened program projects.
    if not check(f"{HOME}/projects"):
        os.mkdir(f"{HOME}/projects")

    exit_code: Optional[int] = None

    exit_code = install.with_mng(["git", "git-delta"])
    if exit_code in [0, 256]:
            link("gitconfig", f"{HOME}/.gitconfig")

    match (install.with_mng(["base-devel"]), install.with_git(["https://aur.archlinux.org/yay.git"], dest="/tmp")):
        case (0 | 256, [0] | [256]):
            subprocess.Popen("makepkg -si", cwd="/tmp/yay", shell=True, bufsize=-1).wait()

    # For vim, we need at least plug.vim
    exit_code = install.with_yay(["vim"])
    if exit_code in [0, 256]:
        install.with_yay(["curl"])
        subprocess.Popen("curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim", shell=True, bufsize=-1).wait()
        link("vimrc", f"{HOME}/.vimrc")
        pass

    # Neovim is builded from source to get the nightly version. We also
    # need to install the packer.nvim to plugins.
    exit_code = install.with_git(["https://github.com/neovim/neovim"], dest=f"{HOME}/projects")
    if exit_code in [[0], [256]]:
        subprocess.Popen("make CMAKE_BUILD_TYPE=RelWithDebInfo", cwd=f"{HOME}/projects/neovim", shell=True, bufsize=-1).wait()
        subprocess.Popen("sudo make install", cwd=f"{HOME}/projects/neovim", shell=True, bufsize=-1).wait()
        install.with_git(["https://github.com/wbthomason/packer.nvim"], dest=f"{HOME}/.local/share/nvim/site/pack/packer/start/packer.nvim", flags=["--depth", "1"])
        link("nvim", f"{HOME}/.config/nvim")

    # Install programs that don't need any explict dependencies
    exit_code = install.with_yay(["picom", "alacritty", "firefox", "rofi", "awesome-git", "feh", "discord", "polybar"])
    if exit_code in [0, 256]:
        link("awesome", f"{HOME}/.config/awesome")
        link("alacritty", f"{HOME}/.config/alacritty")
        link("picom", f"{HOME}/.config/picom")
        link("rofi", f"{HOME}/.config/rofi")
        link("polybar", f"{HOME}/.config/polybar")

    # TODO: install zsh

    # Install and enable sddm.
    if ARGS.sddm and install.with_mng(["sddm"]) in [0, 256]:
        os.system("sudo systemctl enable sddm")
