include ~/.de-config/themes/current/kitty.conf

font_size         14.0
font_family       JetBrainsMono
bold_font         auto
italic_font       auto
bold_italic_font  auto

disable_ligatures never

font_features JetBrainsMonoNFM-Regular +calt +clig +liga +ss20 +cv02 +cv03 +cv04 +cv05 +cv06 +cv07 +cv11 +cv14 +cv15 +cv16 +cv17

enable_audio_bell no
visual_bell_duration 0.15

cursor_trail 1

copy_on_select clipboard

scrollback_lines 10000
scrollback_pager_history_size 64

notify_on_cmd_finish invisible 15
confirm_os_window_close -1
