bindd = SUPER, C,       Kill active client,   killactive,
bindd = SUPER, H,       Focus next client,    layoutmsg,  cycleprev
bindd = SUPER SHIFT, H, Decrease master size, layoutmsg,  mfact -0.05
bindd = SUPER, L,       Focus prev client,    layoutmsg,  cyclenext
bindd = SUPER SHIFT, L, Increase master size, layoutmsg,  mfact +0.05
bindd = SUPER, V,       Cycle orientation,    exec,       de-layout-orientation-cycle
bindd = SUPER, N,       Swap with master,     layoutmsg,  swapwithmaster
bindd = SUPER, J,       Add master,           layoutmsg,  addmaster
bindd = SUPER, K,       Remove master,        layoutmsg,  removemaster
bindd = SUPER, M,       Toggle maximize,      fullscreen, 1
bindd = SUPER, F,       Toggle fullscreen,    fullscreen, 0

bindd = SUPER ALT,   X, Next monitor,                      split-changemonitor,   next
bindd = SUPER SHIFT, 1, Move active client to workspace 1, split-movetoworkspace, 1
bindd = SUPER SHIFT, 2, Move active client to workspace 2, split-movetoworkspace, 2
bindd = SUPER SHIFT, 3, Move active client to workspace 3, split-movetoworkspace, 3
bindd = SUPER SHIFT, 4, Move active client to workspace 4, split-movetoworkspace, 4
bindd = SUPER SHIFT, 5, Move active client to workspace 5, split-movetoworkspace, 5
bindd = SUPER SHIFT, 6, Move active client to workspace 6, split-movetoworkspace, 6
bindd = SUPER SHIFT, 7, Move active client to workspace 7, split-movetoworkspace, 7
bindd = SUPER SHIFT, 8, Move active client to workspace 8, split-movetoworkspace, 8
bindd = SUPER SHIFT, 9, Move active client to workspace 9, split-movetoworkspace, 9
bindd = SUPER SHIFT, 0, Move active client to scratchpad,  movetoworkspace,       special:special

bindm = SHIFT, mouse:276, movewindow   # 272
bindm = SHIFT, mouse:275, resizewindow # 273
