bindd = SUPER, 1, Switch to workspace 1, split-workspace,         1
bindd = SUPER, 2, Switch to workspace 2, split-workspace,         2
bindd = SUPER, 3, Switch to workspace 3, split-workspace,         3
bindd = SUPER, 4, Switch to workspace 4, split-workspace,         4
bindd = SUPER, 5, Switch to workspace 5, split-workspace,         5
bindd = SUPER, 6, Switch to workspace 6, split-workspace,         6
bindd = SUPER, 7, Switch to workspace 7, split-workspace,         7
bindd = SUPER, 8, Switch to workspace 8, split-workspace,         8
bindd = SUPER, 9, Switch to workspace 9, split-workspace,         9
bindd = SUPER, 0, Toggle scratchpad,     togglespecialworkspace, special

bindd = SUPER ALT, 1, Switch to monitor 1, focusmonitor, 0
bindd = SUPER ALT, 2, Switch to monitor 2, focusmonitor, 1

# bindd = SUPER, mouse_down, Scroll to the next workspace workspace,     e+1
# bindd = SUPER, mouse_up,   Scroll to the previous workspace workspace, e-1
