general {
    lock_cmd         = zsh -c "de-lock"
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd  = hyperctl dispatch dpms on
    on_unlock_cmd    = zsh -c "de-restart"
}

# set monitor backlight to minimum in 3 min
listener {
    timeout    = 180
    on-timeout = brightnessctl -s set 10
    on-resume  = brightnessctl -r
}

# turn off keyboard backlight in 3 min
listener { 
    timeout    = 180
    on-timeout = brightnessctl -sd rgb:kbd_backlight set 0
    on-resume  = brightnessctl -rd rgb:kbd_backlight
}

# lock screen in 6 min
listener {
    timeout    = 360
    on-timeout = loginctl lock-session
}

# screen off in 6 min
listener {
    timeout    = 360                                           # 6 min
    on-timeout = hyperctl dispatch dpms off
    on-resume  = hyperctl dispatch dpms on && brightnessctl -r
}

# suspend in 30 min
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
