windowrule = match:class .*, suppress_event maximize
windowrule = match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0, no_focus on

# Ignore borders and gaps when a window is maximized
workspace = f[0]s[false], rounding:false, bordersize:0, gapsout:0
workspace = f[1]s[false], rounding:false, bordersize:0, gapsout:0
