windowrule = match:class ^(Bitwarden)$, float on
windowrule = match:class ^(Bitwarden)$, center on
windowrule = match:class ^(Bitwarden)$, size 60% 70%
windowrule = match:class ^(Bitwarden)$, no_screen_share on
