windowrulev2 = float, class:^(gum-notification-menu)$
windowrulev2 = size 400 300, class:^(gum-notification-menu)$
windowrulev2 = move 100%-410 40, class:^(gum-notification-menu)$

windowrulev2 = float, class:^(gum-webapp-menu)$
windowrulev2 = size 700 500, class:^(gum-webapp-menu)$
windowrulev2 = center, class:^(gum-webapp-menu)$
