windowrule = match:class ^(gum-notification-menu)$, float on
windowrule = match:class ^(gum-notification-menu)$, size 400 300
windowrule = match:class ^(gum-notification-menu)$, move 100%-410 40

windowrule = match:class ^(gum-webapp-menu)$, float on
windowrule = match:class ^(gum-webapp-menu)$, size 700 500
windowrule = match:class ^(gum-webapp-menu)$, center on
